service: yugioh-deck-checker

frameworkVersion: "4"

provider:
  name: aws
  region: eu-west-2
  deploymentBucket:
    name: serverless-framework-deployments-eu-west-2-64e991aa-8c1a
  ecr:
    images:
      api:
        path: ./api
        file: Dockerfile
        platform: linux/amd64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource: "arn:aws:dynamodb:eu-west-2:*:table/jobs"

functions:
  api:
    image:
      name: api
    timeout: 30
    memorySize: 1024
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: yugioh-deck-checker-jobs
        AttributeDefinitions:
          - AttributeName: job_id
            AttributeType: S
        KeySchema:
          - AttributeName: job_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
