name: Production Deployment

on:
  push:
    branches:
      - main
      - feature/frontend

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::082624796438:role/deployment_yugioh-deck-checker

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to production
        run: |
          serverless deploy --stage prod
          serverless info --verbose --stage prod
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Get CloudFormation outputs
        id: stack_outputs
        run: |
          OUTPUTS=$(aws cloudformation describe-stacks \
            --stack-name yugioh-deck-checker-prod \
            --query "Stacks[0].Outputs" \
            --output json)
          echo "$OUTPUTS" > outputs.json
          echo "FRONTEND_BUCKET=$(jq -r '.[] | select(.OutputKey=="FrontendBucketName") | .OutputValue' outputs.json)" >> $GITHUB_ENV
          echo "API_URL=$(jq -r '.[] | select(.OutputKey=="HttpApiUrl") | .OutputValue' outputs.json)" >> $GITHUB_ENV
          echo "CLOUDFRONT_ID=$(jq -r '.[] | select(.OutputKey=="CloudFrontDistributionId") | .OutputValue' outputs.json)" >> $GITHUB_ENV

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          VITE_API_URL=${API_URL} npm run build

      - name: Deploy frontend to S3
        run: |
          aws s3 sync ./frontend/dist s3://${FRONTEND_BUCKET} --delete --cache-control max-age=31536000

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1WR0ZKN4NI12D \
            --paths "/*"
